export enum Route {
  CREATE_APPOINTMENT = 'create',
  SCHEDULE_APPOINTMENT = 'schedule',
  APPOINTMENTS = 'appointments',
  HOME = '',
  CALLBACK = 'callback',
  CREATE_CENTER = 'createc',
  CREATE_STAFF = 'new-staff',
  CENTERS = 'centers',
  USER_REVIEW = 'user-review',
  QUESTIONNAIRE = 'questionnaire',
  USER_INFO = 'user-info',
  TENDERS = 'tenders',
  MY_APPOINTMENTS = 'my-appointments',
  PREFERED_APPOINTMENT = "prefered-appointment",
  CENTER_APPOINTMENTS = "center_appointments",
  CALENDAR = "calendar",
  CREATE_ADMIN = "new-admin",
  DELIVERY = "location-tracker/check"
}
